# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
    - CONDA_R=3.4.1
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "IPyW/+pI6V4ai0XGkZLM2D3Y9o8Ff5BMevAJ9lr0Sh7ZbdglBAvtCsMD+5FBOTc5/0QLQSx63O6RJlbRT5f1x40n5qX03Rmgno0GuKtbUURVaMSugpt4HQ4mUZMt8X9q7lBvJJ7xpxT4RjPzZEheBEa45Qu1d+rs6WBSPwFmLA5ntSMlfpSacgNYTF420COjrN9nOb2wkGJkNFOpHY9g1rvtpDOH52By5OoUeGFKdUYr8G5kFtLI5w2f+/zfcNbu6YiWflfaqlIf/wOTISV+WvQ9czP9+mBCEQHYyKI52KNOl39F9GKPpqio3MsTaonuyeNq6QSeq5HwC6EFPhCKRj17z1vVQm5tb/UMTrMnduFoe6cpFIu+JuOHCQ4n/DeYR63KT8N1oIeUOFUpHQqE+LRnEQ5cASRHILMolJ9Qf1cAH/MKRkVTeg9IBVJjpgTpREvTpPNa3v3p2VduY5gEN0esxVRPoxcRHPIYKywzScK3gUCj7p4yxK22563bcR+hqvfriIDIiXRZpWj4D8a5Bvwoiio5SHqtu+o+9L8PQoznizIMKG2dxm82FPdqS7AD8RrbfinezTeLCRj89T7d8jRanF5o/u+95tYySOMUJUGkmJXH3hHT6XvZ/ArOcER2+qz1IbV3F/XO60CK68pYRY55SLJoUFNMAYVN8D81ceU="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
