travis:
  secure:
    BINSTAR_TOKEN: IPyW/+pI6V4ai0XGkZLM2D3Y9o8Ff5BMevAJ9lr0Sh7ZbdglBAvtCsMD+5FBOTc5/0QLQSx63O6RJlbRT5f1x40n5qX03Rmgno0GuKtbUURVaMSugpt4HQ4mUZMt8X9q7lBvJJ7xpxT4RjPzZEheBEa45Qu1d+rs6WBSPwFmLA5ntSMlfpSacgNYTF420COjrN9nOb2wkGJkNFOpHY9g1rvtpDOH52By5OoUeGFKdUYr8G5kFtLI5w2f+/zfcNbu6YiWflfaqlIf/wOTISV+WvQ9czP9+mBCEQHYyKI52KNOl39F9GKPpqio3MsTaonuyeNq6QSeq5HwC6EFPhCKRj17z1vVQm5tb/UMTrMnduFoe6cpFIu+JuOHCQ4n/DeYR63KT8N1oIeUOFUpHQqE+LRnEQ5cASRHILMolJ9Qf1cAH/MKRkVTeg9IBVJjpgTpREvTpPNa3v3p2VduY5gEN0esxVRPoxcRHPIYKywzScK3gUCj7p4yxK22563bcR+hqvfriIDIiXRZpWj4D8a5Bvwoiio5SHqtu+o+9L8PQoznizIMKG2dxm82FPdqS7AD8RrbfinezTeLCRj89T7d8jRanF5o/u+95tYySOMUJUGkmJXH3hHT6XvZ/ArOcER2+qz1IbV3F/XO60CK68pYRY55SLJoUFNMAYVN8D81ceU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
