travis:
  secure:
    BINSTAR_TOKEN: nrM6s8WYHEo2oWrkxS1/NINupawhDD0a0DIoQfcQQglat4LHr537GVAreWsclOG05hlHTRAFz4f29kxVqI0GUr/6ykdPUjewqEH1beZqh0gqlb8WgUTMB41yfGU0s3cze4RS1vajG1diGtekgSHhMRw2hy3Vorck+Oxdch3ee2t6C5+0G7ycP9vvsb8EoNgkYAi3JtHOlMlX/VD+Hycqh37vGU6sLCoixdpIu4kIv3Z+9rkLJyYO6uU6uNSl1nuLNdnoQM9Rft/VpQq8MosGPo5N6+56tR9K3IxPJYSPESxpXq/jjr+atTe7GB+K0ttBie3O9MKdCqj/pHK+FrrnFQq2uN0Gra7EAaNM67f6+glubLN8QTg1TRWiCvbjUwYXXLAle96n2XOzx80cYpzbngqnk+YfE97xstF2WEFNG9q1f1KA9oI5G4jicHYxvz+OtisKehmZ3EBhTcd0y/R+8KwSzsl9yst3gxcJFunncjA3Z6jqLSEP8XdsFaElvJ5yI4KQTIOX++PUj7fkeAFUPwwEjA11ut5QbBExurMI4ZRSOlILp/zB3Zl98pNifIfzciymlO+kffkneHmBD+KIk2YRtXPZQgmd1bTDO0eGwDAFey3LMICWs0ug0O7mVRZfIDRf0x/jujMJ7TophsoAvQuhFAPMfxq+Qa4wYDJ93iM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
