travis:
  secure:
    BINSTAR_TOKEN: pyavuaQ0zOqITLDFI6fW1JZVwtdfNiDk4iuZfo8xajtx75GGtNg3xHsV/kXRh4Wx3yN0+79whvITkDGPSam8aDKbw0hgr+mgs9MuFkHZwswSr23n/2Ss9May1A78UF7Cf/wRyfaxNpgKhX5KQtSU7S2FQDlWIOJIUoy+nCJx82zqWyEGOg0bTwuJzRCeC4bFKrEjDEsZSsZn080fhxYhJfrUmRI1MaENJhjLIK+laVrPsIC2WtA2izjzbd+VakNl1jQvHP7RquZXRvJpRIoNdRIK08N0LLjS6WCAWKuRwAnNhavX0HArFMs/p5iC8Cot22BNVUeybiT4IJvRjuvI0yNoCdmPIRPrc4svTLSSHrUWM6cp164MFq5fsMBDNEi4PHYMRu548Ez4fLidGfqKzDYvCLX/BTd/lPuhD6yEQ7H/XZUSwKhMGgHR9WM+hsuYVbUQY9s+mdNQPXpdvWhusIz3vRWcdYyjUyocZpSOtT+spP3+jlBLIGYSjbV/lK4+uWE9ajLdIhsSURs6PeVaDTa5tsNWRKSe5qKgSFxA8G8X1tYVxM/x/ADSzxFNPkxZrtqQEu2R+XZg+oIqXvDxZa/4/JlqGZYUglyf3UNTWSb5vx6dHibeRVTqQBfbUZazdLk862WgP1YBY4unF0nTcw/P+lj1kTn0vESI9KZkYts=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
