travis:
  secure:
    BINSTAR_TOKEN: sOB3liJiWX/4URsLPdQor/OYMAbOsGahI3Jo7D7U3OmB6HWDcyXFwE2rbwqmtz6JCRMlRYFTFTFl3yBGTkh1SIYjuZ81Cyxqm/R0andRnbY10VlQqB/p8S/vaQx42WBZejdypxCKUOp21/ibLC1bQaoWr+aEyfR3t9nCz2CVOFXGZcYsOIMSjxY3s7DJmUEQdC7BweN+/4p6nm3nStx2+1L+nBULyctpSXpAa3ibir8lEuEW/v3UNz+eXueVcvGgdzgmh2Gt/S7s15v7j1RJeLarMrlcZP1M/jIQyUKt4nsSxqHZxS4ps9rl08cVeg7hF88sKUfBRa0Rp/bTnLcXDUzEYsMkYKRa9F0uxdeaJEh3Sx40XFy+HCYuMunqKelpZ9h8uNdRg7CEIZuVop/XvU0f8DSmUH/LYyEkaZLp4mLBlcLxcXGL1WTh1pCIVHYw240qyEECEh5HMMvuFfzvs3lf4w/OCh9RcnMFZXICLFhcb9X6z5QTLqpdw4olmSD68WBTlwKKeDeOVfl/slivatXpQzFTLsl8NYzX01O7JeQPLQYhUrzCvAJJun0LUHfmT0PfH8ti1UK+5GVSskiKpi4wafMKZT4LQoysAX+xcPwZgxU2sugzcXbYBJGEXk17kgxD38UfwnrbPyf90H8VYhXepbwWZn5R97sZouAGIqY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
