appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: lSiJfs8qmpNrLbSHs0PB/Uzt5atO875CLMgXSQuzmNR/z1/tmyG/rhho5BtFTnGraGV7RLQV4wxB1UQkn/hDjvAbH8C5+kuWnmwRbBXI4E5zdLXJ8edcHsZBffDlhSjGQPO2R23QP6xsCQatkaObLYefoZqabWjd07dc4Nwej328cC3WPmWTdqO3X1fgL8UShk/YssBwdpJEbaeRJhXz18YKcZdBxykQF9UjsfVchNHkND9LiNzS8QY3a3CxHis3u4tRDlXLKxyaR2bPag8zglupE1lgbDrPbp8QOSiSwURsncPMBy90UAa69N7Vxgpz9C9I/Z9tj+7dW1dmAHBYYrBAGxt+1Ub1YAzASrhciTUJG6zrdDBzjwTbgLHIZ45hb2cZNHbE/2f179hFA76TcHHMeId5lhjeFuvVlwGZxZuVF9/Gr9kp8vULDPsOuxK/i2fkPjQGd/TtjogORFZeN2VGaS3CS89FaFvtF4/L201kzYwRAJy8wYfUcLB1f1Ey2r9lkQR/7n6U1vS2ufAY6MgymNpsUZgklcMWOoEsfM4QeT1t+JqmkaxdL60f0x1lRKvExDa8AtfgxcCMy2ExnV/TQTzg03LZlyHY2D1mJ1wVr49n4KnZeh1Qdyqe40oyyTe6/a7F2BSOd80MSb7SnUnlalFLOIldK9P/WOYwxtY=
